language: php
php:
- 7.1
- 7.2
- 7.3
- hhvm
matrix:
  allow_failures:
  - php: hhvm
  fast_finish: true
before_script:
- composer self-update
- composer install --dev
- composer require satooshi/php-coveralls:* --dev
script:
- mkdir build/coverage
- phpunit
after_success:
- php vendor/bin/coveralls -v -c .coveralls.yml
- if [ $TRAVIS_PHP_VERSION = '5.6' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh generate-api.sh; fi
notifications:
  email:
    recipients:
    - travis@josecelano.email
    on_success: change
  slack:
    secure: V7qdh0pYk2J0mchOuqqHT7KJoejkCzM6gH7fBoOuvGE1lzvJikQIugZd/X995AA+EdLbNFszOq7qP6zq2LFE4aDmN+MuHDz9cqow49TnT0gWlgeMZAYgP8JhiqXXxxZJD0fJa/WtQTwJ0Ya0R/fl4lHOEioMFkzIXjD+QhAwYTXkNBVRJAO74FbTbNrsutmrB+LCiolDcEPuNmgBl+l7jq5H7aOrSMR27Rox5xPVUY7R0RVVsXfYEHYC/1hzS5cfZQAFH8wpLQYSXkZIfOF+QnVvl8em2JlNwNIsI/Ml/rGtGgOsWFQ4+VcPwVxECbxP2OXlDER/WkFEax2LMeGRtW3NdlGlTqhYnKHRrBY4P9+peyvkRbmvlZfB2CiI1xw9fb0CMbByNnuyQcP3j2Ve8au9eRvEukTK6gWavCi22BDBwcnOyFJBWuk418qhWbX14esip8CuDrgf5yktHJF3lerGyUgTGeMmzjeEBnu0UaEt1ejlb730eoHhfy9O1RnA/xt8aJaIkPcvfwRaYK9U7/GGM17YSKb509s0pN2+Hha3/IPLM5DFec92qCwQ0FohoGEb/Gqgx2meb0eEp7qrkSY0Oc31KYJBZVydauqg5Lplk217RbcLe/juh03BiqHCj5jhto9WMqyo83RikwgHtl/2Y1tby3TCey0Z9U4y3OE=
env:
  global:
  - secure: nlWeUxzHfhYRFDaUIDDwTJ3bUwmwfb6iJrbNMmBi8+4HuHjp1RKwMZ7tbLJb9p8YVYP3NF0NtJQzFoLdLESJamebtr+UDfQ/Cn0mneriqyI4NKvg5yj86Ggxn7tmVDrp/R5pzBUurDLh7VMlKN82HIFpVa8W4wFwkYUet5yhrZJKvBcAE+M0/iysHjS/AamC6h6tV4woaOcR7CTJTwu3EDs28aeSRkxVabMWuW4o/2ZwqtM8yN5S4C4h67liif8Adcb1vrqO9WjV4dfn67g8PNdB5KoqaHs9Om9u0Px/LCk/wQTYCbVrayeytND0BhSKBRylNRWa5SzTYXZaNuGLkoLU2sgPS42WxCmhMQE6Zp0oJy9jcrC7FPEsdvfQ0AuDi79NLm3FibXDa6MZaxzvs3vvw0NhYeVyYp23hw/j0U1tK9r9gNrS0o1COXAJd5rNWNpQpae4XCS4Y1aByR+L75r4L6bhmjtvvAZkX0cLJLm04eur5kILjnTsMcp5btihTNiFPEIQv0c+gkbaJjzgpzkFr+OUY0Gtw3poWQtmGyAFn1zXs+qWwSDpmjJR96EegAvJ4hqaHD2iU2AQoc5A6LC2OsEw7jDcpqmtq7Lk5XbKDqtvWx5gX7LnKpMRGQ1/r/u3WQnYMh8AtdKyjmcbzU8uX31SGOjQPzGinacRgSs=
